### PR TITLE
Draw annotation

### LINKED ISSUE #28: Error handling
Currently, we don't any sort of error handling in this project. We're making a lot of assumptions, and the code can easily break if any of those assumptions are not met. 

In this issue, I will outline what would be the desired error handling method in OSD viewer. I will not mention any specific errors and will just outline all the possible/preferable ways that we could handle errors. As the next step, @rastogi-bhavya  should list all the errors that OSD viewer might throw. Then we can be more specific about how we want to handle each of them. Or whether we need to implement all or parts of the error handling methods that are outlined here.

## Error types
We can categorize errors into two general categories:

1. Internal: errors that can be solved/reported within the osd viewer and won't propagate to Chaise.
2. External: errors that have to be reported to Chaise. 

In both categories, an error can either:
- cause the whole app to break. We should show a popup that disables/hides all the controls on the page, shows a proper message, and offer ways to resolve the error.
- disable a feature. In this case, we could show some sort of alert/warning to the users to inform them of the issue. Or we might want to fail silently and only report the issue in the console.

As I mentioned I'm not familiar with all features of the app, so I won't list the errors. We should create an `errors.js` file that will be the place that we define all these different types of errors. We should try to follow the same code style that is used in the repository, but for reference you can take a look at [`ermrestjs`](http://github.com/informatics-isi-edu/ermrestjs/blob/master/js/errors.js) or [`Chaise`](https://github.com/informatics-isi-edu/chaise/blob/master/common/errors.js) examples. 

(I'm not trying to dictate the implementation here, but the error prototype should define the external vs. internal, as well as warning vs. actual error. We might want to have a hierarchy of these prototypes.)  

## How to handle errors 
If we want to mimic the same mechanism that is used in Chaise, we first need to define some sort of "global" error handler. Since Chaise is using Angular built-in features, we cannot have the exact same mechanism here. We can use the [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror). This will catch _any uncatched_ Javascript error that is thrown from anywhere on the page.

By leveraging this, we can throw errors from different locations in the code, and then we can handle them in the common `window.onerror` function. The callback function can then decide how it should handle the error. Whether it's going to be blocking or just warning. Whether it should send a message to Chaise or just handle it in OSD.  

Although, in some cases, we might want to handle an error locally without leaving it unhandled. We should review this when we have the list of errors, but I feel like for the warning messages it might be easier to call some predefined callback in our code to handle the warnings. The most important benefit of using `window.onerror` is the fact that you don't need to worry about "unhandled" errors. Errors that might be thrown because of some unforeseen code path. But if we're the ones that are manually throwing error, we can just call a predefined callback instead.

### PR DESCRIPTION
**Pull request by rastogi-bhavya**
This PR will add the ability to draw annotations to an image. The initial changes were done by @iamyle0710 and @vipul-21 . @RFSH and I later added some more changes to this branch.

The changes that have been done

- Drawing tools were added. We can now draw line, rectangles and circles on the images using these tools. After drawing, the annotation can be saved.

- Support for SVG for different file format has also been added.

- Make file was added to the viewer

- Output SVG format corrections. Made sure that the SVG that was created by using the drawing tools, conformed to the SVG standards #31 

- Empty element fix #28 

- Added enableSVGStrokeWidth as a URL param, which decides whether to use the SVG stroke-width or not.

- Fixed the tooltip bug where the tooltip would not disappear when, while drawing the SVG component was deleted without saving it.

### CODE REVIEW

File: js/viewer/annotation/base.js [hunk 1]
```diff
@@ -2,35 +2,132 @@ function Base(attrs){
...
+        }
+
+        for(attr in this._attrs){
+            // Ingoring style because that will be added at the end.
+            // Ignoreing vector-effect becasue this properpty is not needed in the output file
+            if (!this._attrs[attr] || this._attrs[attr] === null || attr === "style" || attr == "vector-effect"){
+                continue;
+            }
+
+            switch(attr){
```
Comment (RFSH) [inline js/viewer/annotation/base.js:79]: The first two `case`s in this switch is the same as the `attr === 'style'` and `attr == "vector-effect"` that you added (both methods are just ignoring those attributes) Combine these so your code should be like this

```javascript
var ignoredAttributes = ["style", "vector-effect", "tag", "graph-id"];

for(attr in this._attrs){
  if (this._attrs[attr] == null || ignoredAttributes.indexOf(this._attrs[attr]) != -1) continue;

  rst += (attr + '="' + this._attrs[attr] + '" ');
}
```

You could make this more optimized but this is fine for now.

File: js/viewer/annotation/base.js [hunk 2]
```diff
@@ -78,6 +212,14 @@ Base.prototype.renderSVG = function(){
             .on("mousemove", this.onMousemoveShowTooltip)
             .on("mouseout", this.onMouseoutHideTooltip)
             .on('click', this.onClickToSelectAnnotation);
+            
+        // prevent the default behavior of osd by adding an empty click handler
+        new OpenSeadragon.MouseTracker({
```
Comment (RFSH) [inline js/viewer/annotation/base.js:217]: I know I added this, but I didn't know we have an `unbind` function. I think we should capture this object and destroy it in the unbind function, so

```javascript
this._defaultClickHandler = new OpenSeadragon.MouseTracker({
  element: this.svg.node(),
  clickHandler: function (e) {
    // intentially left empy. we just want to prevent the default behavior (zoom)
  }
});

```

Then in the `unbind` we should just do 

```
if (this._defaultClickHandler) {
  this._defaultClickHandler.destroy();
}
```
(we should test and make sure this works properly)

File: js/toolbar/annotation-tool.js [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+                "<span class='toolBtn' data-type='RECT'>",
+                    "<i class='fa fa-square'></i>",
+                "</span>",
+                "<span class='toolBtn' data-type='CIRCLE'>",
+                    "<i class='fa fa-circle'></i>",
+                "</span>",
+                "<span class='toolBtn' data-type='ERASER'>",
+                    "<i class='fa fa-eraser'></i>",
+                "</span>",
+                // "<span class='toolBtn' data-type='SAVE'>",
```
Comment (RFSH) [inline js/toolbar/annotation-tool.js:70]: These three lines should just be removed.

File: js/toolbar/toolbar.view.js [hunk 4]
```diff
@@ -75,19 +93,22 @@ function ToolbarView(controller, config){
...
             switch(type){
                 case "channelList":
-                    this.renderChannelContent(list);
+                    this.renderChannelContent(object);
                     break;
                 case "annotationList":
-                    this.renderAnnotationGroupContent(list);
+                    this.renderAnnotationGroupContent(object);
                     break;
+                // case "annotationTool":
```
Comment (RFSH) [inline js/toolbar/toolbar.view.js:109]: we should remove this one. we shouldn't leave commented code paths like this without any comments why it's commented. If the feature is not needed, we just remove the code.

File: js/viewer/annotation/base.js [hunk 5]
```diff
@@ -2,35 +2,132 @@ function Base(attrs){
     attrs = attrs ? attrs : {};
     var _self = this;
     this.parent = attrs.parent;
+    this.id = attrs["graph-id"] || -1;
```
Comment (RFSH) [inline js/viewer/annotation/base.js:5]: What's the purpose of `graph-id` attribute?
